export const DEFAULT_ATTRIBUTION_VERBS = ["acknowledged", "added", "admitted", "advised", "affirmed", "agreed", "announced", "answered", "argued", "asked", "barked", "began", "bellowed", "blurted", "boasted", "bragged", "called", "chirped", "commanded", "commented", "complained", "conceded", "concluded", "confessed", "confirmed", "continued", "countered", "cried", "croaked", "crowed", "declared", "decreed", "demanded", "denied", "drawled", "echoed", "emphasized", "enquired", "enthused", "estimated", "exclaimed", "explained", "gasped", "insisted", "instructed", "interjected", "interrupted", "joked", "lamented", "lied", "maintained", "moaned", "mumbled", "murmured", "mused", "muttered", "nagged", "nodded", "noted", "objected", "offered", "ordered", "perked up", "pleaded", "prayed", "predicted", "proclaimed", "promised", "proposed", "protested", "queried", "questioned", "quipped", "rambled", "reasoned", "reassured", "recited", "rejoined", "remarked", "repeated", "replied", "responded", "retorted", "roared", "said", "scolded", "scoffed", "screamed", "shouted", "sighed", "snapped", "snarled", "spoke", "stammered", "stated", "stuttered", "suggested", "surmised", "tapped", "threatened", "turned", "urged", "vowed", "wailed", "warned", "whimpered", "whispered", "wondered", "yelled"];

export const DEFAULT_ACTION_VERBS = ["adjust", "adjusted", "appear", "appeared", "approach", "approached", "arrive", "arrived", "blink", "blinked", "bow", "bowed", "charge", "charged", "chase", "chased", "climb", "climbed", "collapse", "collapsed", "crawl", "crawled", "crept", "crouch", "crouched", "dance", "danced", "dart", "darted", "dash", "dashed", "depart", "departed", "dive", "dived", "dodge", "dodged", "drag", "dragged", "drift", "drifted", "drop", "dropped", "emerge", "emerged", "enter", "entered", "exit", "exited", "fall", "fell", "flee", "fled", "flinch", "flinched", "float", "floated", "fly", "flew", "follow", "followed", "freeze", "froze", "frown", "frowned", "gesture", "gestured", "giggle", "giggled", "glance", "glanced", "grab", "grabbed", "grasp", "grasped", "grin", "grinned", "groan", "groaned", "growl", "growled", "grumble", "grumbled", "grunt", "grunted", "hold", "held", "hit", "hop", "hopped", "hurry", "hurried", "jerk", "jerked", "jog", "jogged", "jump", "jumped", "kneel", "knelt", "laugh", "laughed", "lean", "leaned", "leap", "leapt", "left", "limp", "limped", "look", "looked", "lower", "lowered", "lunge", "lunged", "march", "marched", "motion", "motioned", "move", "moved", "nod", "nodded", "observe", "observed", "pace", "paced", "pause", "paused", "point", "pointed", "pop", "popped", "position", "positioned", "pounce", "pounced", "push", "pushed", "race", "raced", "raise", "raised", "reach", "reached", "retreat", "retreated", "rise", "rose", "run", "ran", "rush", "rushed", "sit", "sat", "scramble", "scrambled", "set", "shift", "shifted", "shake", "shook", "shrug", "shrugged", "shudder", "shuddered", "sigh", "sighed", "sip", "sipped", "slip", "slipped", "slump", "slumped", "smile", "smiled", "snort", "snorted", "spin", "spun", "sprint", "sprinted", "stagger", "staggered", "stare", "stared", "step", "stepped", "stand", "stood", "straighten", "straightened", "stumble", "stumbled", "swagger", "swaggered", "swallow", "swallowed", "swap", "swapped", "swing", "swung", "tap", "tapped", "throw", "threw", "tilt", "tilted", "tiptoe", "tiptoed", "take", "took", "toss", "tossed", "trudge", "trudged", "turn", "turned", "twist", "twisted", "vanish", "vanished", "wake", "woke", "walk", "walked", "wander", "wandered", "watch", "watched", "wave", "waved", "wince", "winced", "withdraw", "withdrew"];

export const EXTENDED_ATTRIBUTION_VERBS = [
    'acknowledged', 'added', 'addressed', 'admitted', 'affirmed', 'agreed',
    'announced', 'answered', 'appealed', 'argued', 'articulated', 'asserted',
    'assured', 'avowed', 'babbled', 'bantered', 'barked', 'bawled', 'begged',
    'bellowed', 'blathered', 'blurted', 'boasted', 'bragged', 'breathed',
    'bubbled', 'called', 'cautioned', 'chanted', 'chatted', 'chirped',
    'chortled', 'chuckled', 'clamored', 'clarified', 'commanded',
    'commented', 'confessed', 'confided', 'confirmed', 'congratulated',
    'continued', 'countered', 'croaked', 'crowed', 'cried', 'declared',
    'decreed', 'defended', 'demanded', 'denied', 'drawled', 'droned',
    'emphasized', 'enquired', 'enthused', 'exclaimed', 'explained', 'expostulated',
    'gasped', 'giggled', 'grinned', 'groaned', 'growled', 'grumbled',
    'grunted', 'hissed', 'hollered', 'howled', 'implored', 'implied',
    'insisted', 'intoned', 'intimated', 'interjected', 'interrupted',
    'inquired', 'jabbered', 'jested', 'joked', 'lamented', 'laughed',
    'maintained', 'marveled', 'mewled', 'mimicked', 'mumbled', 'murmured',
    'mused', 'muttered', 'nagged', 'noted', 'observed', 'offered', 'opined',
    'orated', 'ordered', 'pleaded', 'posited', 'prattled', 'preached',
    'pronounced', 'proclaimed', 'professed', 'proffered', 'promised',
    'proposed', 'protested', 'purred', 'queried', 'questioned', 'quipped',
    'quoted', 'rambled', 'rasped', 'reassured', 'rebuked', 'recited',
    'remarked', 'reminded', 'repeated', 'replied', 'reported', 'requested',
    'responded', 'retorted', 'revealed', 'roared', 'scolded', 'screeched',
    'shouted', 'shrieked', 'sighed', 'snapped', 'sneered', 'snickered',
    'sniped', 'snorted', 'sobbed', 'soothed', 'speculated', 'spluttered',
    'spoke', 'sputtered', 'stammered', 'stated', 'suggested', 'surmised',
    'taunted', 'teased', 'threatened', 'trilled', 'twittered', 'uploaded',
    'uttered', 'vowed', 'wailed', 'warned', 'whimpered', 'whined',
    'whispered', 'whooped', 'wondered', 'yelled', 'yelped', 'yowled',
];

export const EXTENDED_ACTION_VERBS = [
    'ambled', 'angled', 'ascended', 'assembled', 'attacked',
    'balanced', 'beckoned', 'bolted', 'bounded', 'braced', 'brandished',
    'bristled', 'brushed', 'burrowed', 'bustled', 'calibrated', 'careened',
    'carved', 'cast', 'charged', 'chased', 'clambered', 'clapped', 'clashed',
    'clutched', 'coiled', 'collided', 'commanded', 'conjured', 'contemplated',
    'cowered', 'cradled', 'crashed', 'creaked', 'crept', 'crooned',
    'crumpled', 'crushed', 'darted', 'dashed', 'deflected', 'descended',
    'dipped', 'dodged', 'dragged', 'drained', 'drifted', 'drummed',
    'embraced', 'entwined', 'faltered', 'fidgeted', 'flew', 'flinched',
    'flitted', 'flourished', 'fluttered', 'focused', 'forged', 'galloped',
    'gathered', 'gazed', 'glanced', 'glided', 'glimmered', 'glinted',
    'glowered', 'gnashed',
    'grimaced', 'grinned', 'gripped', 'groaned', 'ground', 'hacked',
    'halted', 'hammered', 'harnessed', 'heaved', 'hissed', 'hovered',
    'huddled', 'hustled', 'illuminated', 'inched', 'intercepted', 'jolted',
    'jostled',
    'kindled', 'knelt', 'knitted', 'laughed', 'launched', 'leaned', 'leapt',
    'lingered', 'loomed', 'lurched', 'lunged', 'massed', 'meandered',
    'melted', 'mended', 'merged', 'mimed', 'motioned', 'mustered', 'muttered',
    'navigated', 'nodded', 'nudged', 'observed', 'paced', 'paddled', 'paused',
    'peered', 'perched', 'pivoted', 'planted', 'plotted', 'plucked',
    'plummeted', 'pounced', 'pranced', 'pressed', 'prodded', 'prowled',
    'pulled', 'punched', 'pursued', 'raced', 'radiated', 'rallied', 'reeled',
    'reached', 'retreated', 'reversed', 'revolved', 'roared', 'rocked',
    'rolled', 'sailed', 'sallied', 'savored', 'screeched', 'seized', 'shaded',
    'shadowed', 'shimmered', 'shouted', 'shrugged', 'shuddered', 'sidestepped',
    'sifted', 'sighed', 'sketched', 'skidded', 'skimmed', 'slashed', 'slithered',
    'sluiced', 'smirked', 'smote', 'snapped', 'sneered', 'snickered',
    'sniffed', 'snorted', 'soared', 'sparked', 'spilled', 'spiraled',
    'sprawled', 'sprinted', 'sputtered', 'squared', 'squeezed', 'staggered',
    'stilled', 'stooped', 'stormed', 'straddled', 'strayed', 'stretched',
    'strode', 'strolled', 'struggled', 'strummed', 'strutted', 'summoned',
    'swirled', 'swiveled', 'swung', 'tailed', 'tensed', 'thrashed', 'threw',
    'thrust',
    'thudded', 'tipped', 'toppled', 'tracked', 'traced', 'trailed',
    'tramped', 'trickled', 'trudged', 'twirled', 'twisted', 'unsheathed',
    'vaulted', 'veered', 'waded', 'waited', 'wandered', 'warped', 'watched',
    'whirled', 'whispered', 'whistled', 'widened', 'winced', 'wove',
    'wrestled', 'wriggled', 'yanked', 'yearned', 'zigzagged',
];
